@extends('layout.app')
@section('tittle', 'home')
@section('content')
    @include('layout.menu')
    @include('components.homeBanner')
    @include('components.service')
    @include('components.course')
    @include('components.HomeProject')
    @include('components.HomeContact')
    @include('components.HomeBlog')
    @include('components.HomeReviews')
    @include('layout.Footer')
@endsection
